// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package bd

import (
	"database/sql"
	"time"
)

type Album struct {
	IDAlbum        int32     `json:"id_album"`
	AlbumName      string    `json:"album_name"`
	AlbumDur       int32     `json:"album_dur"`
	AlbumPh        int32     `json:"album_ph"`
	ReleaseDate    time.Time `json:"release_date"`
	ArtistIDArtist int32     `json:"artist_id_artist"`
	Likes          int32     `json:"likes"`
}

type Artist struct {
	IDArtist   int32  `json:"id_artist"`
	ArtistName string `json:"artist_name"`
	Photo      int32  `json:"photo"`
	ArtistBio  string `json:"artist_bio"`
}

type ArtistSong struct {
	ArtistIDArtist int32 `json:"artist_id_artist"`
	SongIDSong     int32 `json:"song_id_song"`
	Roll           bool  `json:"roll"`
}

type Review struct {
	IDReview     int32         `json:"id_review"`
	ReviewText   string        `json:"review_text"`
	ReviewRate   float64       `json:"review_rate"`
	ReviewDate   time.Time     `json:"review_date"`
	UserIDUser   int32         `json:"user_id_user"`
	SongIDSong   sql.NullInt32 `json:"song_id_song"`
	AlbumIDAlbum sql.NullInt32 `json:"album_id_album"`
	Likes        int32         `json:"likes"`
}

type Song struct {
	IDSong       int32  `json:"id_song"`
	SongName     string `json:"song_name"`
	SongDur      int32  `json:"song_dur"`
	Likes        int32  `json:"likes"`
	AlbumIDAlbum int32  `json:"album_id_album"`
}

type User struct {
	IDUser   int32  `json:"id_user"`
	UserName string `json:"user_name"`
	Amigos   int32  `json:"amigos"`
	Photo    int32  `json:"photo"`
}
