// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package bd

import (
	"context"
	"database/sql"
	"time"
)

const buscarAlbumById = `-- name: BuscarAlbumById :one
SELECT id_album, album_name, album_dur, album_ph, release_date, artist_id_artist, likes FROM Album
WHERE id_album = $1
`

func (q *Queries) BuscarAlbumById(ctx context.Context, idAlbum int32) (Album, error) {
	row := q.db.QueryRowContext(ctx, buscarAlbumById, idAlbum)
	var i Album
	err := row.Scan(
		&i.IDAlbum,
		&i.AlbumName,
		&i.AlbumDur,
		&i.AlbumPh,
		&i.ReleaseDate,
		&i.ArtistIDArtist,
		&i.Likes,
	)
	return i, err
}

const buscarAlbumByName = `-- name: BuscarAlbumByName :many
/* El user no sabrá el id del album, debe poder buscarlo por nombre
    Puede devolver más de uno si es por nombre por si dos albumes se llaman igual */
SELECT id_album, album_name, album_dur, album_ph, release_date, artist_id_artist, likes FROM Album
WHERE album_name = $1
`

func (q *Queries) BuscarAlbumByName(ctx context.Context, albumName string) ([]Album, error) {
	rows, err := q.db.QueryContext(ctx, buscarAlbumByName, albumName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.IDAlbum,
			&i.AlbumName,
			&i.AlbumDur,
			&i.AlbumPh,
			&i.ReleaseDate,
			&i.ArtistIDArtist,
			&i.Likes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO Album (album_name, album_dur, album_ph, release_date, Artist_id_artist, Likes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id_album, album_name, album_dur, album_ph, release_date, artist_id_artist, likes
`

type CreateAlbumParams struct {
	AlbumName      string    `json:"album_name"`
	AlbumDur       int32     `json:"album_dur"`
	AlbumPh        int32     `json:"album_ph"`
	ReleaseDate    time.Time `json:"release_date"`
	ArtistIDArtist int32     `json:"artist_id_artist"`
	Likes          int32     `json:"likes"`
}

// QUERIES DE ALBUM
func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRowContext(ctx, createAlbum,
		arg.AlbumName,
		arg.AlbumDur,
		arg.AlbumPh,
		arg.ReleaseDate,
		arg.ArtistIDArtist,
		arg.Likes,
	)
	var i Album
	err := row.Scan(
		&i.IDAlbum,
		&i.AlbumName,
		&i.AlbumDur,
		&i.AlbumPh,
		&i.ReleaseDate,
		&i.ArtistIDArtist,
		&i.Likes,
	)
	return i, err
}

const createArtist = `-- name: CreateArtist :one
INSERT INTO Artist (artist_name, photo, artist_bio)
VALUES ($1, $2, $3)
RETURNING id_artist, artist_name, photo, artist_bio
`

type CreateArtistParams struct {
	ArtistName string `json:"artist_name"`
	Photo      int32  `json:"photo"`
	ArtistBio  string `json:"artist_bio"`
}

// QUERIES DE ARTIST
func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error) {
	row := q.db.QueryRowContext(ctx, createArtist, arg.ArtistName, arg.Photo, arg.ArtistBio)
	var i Artist
	err := row.Scan(
		&i.IDArtist,
		&i.ArtistName,
		&i.Photo,
		&i.ArtistBio,
	)
	return i, err
}

const createArtistSong = `-- name: CreateArtistSong :one

INSERT INTO Artist_Song (Artist_id_artist, Song_id_song, Roll)
VALUES ($1, $2, $3)
RETURNING artist_id_artist, song_id_song, roll
`

type CreateArtistSongParams struct {
	ArtistIDArtist int32 `json:"artist_id_artist"`
	SongIDSong     int32 `json:"song_id_song"`
	Roll           bool  `json:"roll"`
}

// QUERIES DE ARTIST_SONG (MANY TO MANY)
func (q *Queries) CreateArtistSong(ctx context.Context, arg CreateArtistSongParams) (ArtistSong, error) {
	row := q.db.QueryRowContext(ctx, createArtistSong, arg.ArtistIDArtist, arg.SongIDSong, arg.Roll)
	var i ArtistSong
	err := row.Scan(&i.ArtistIDArtist, &i.SongIDSong, &i.Roll)
	return i, err
}

const createReview = `-- name: CreateReview :one

INSERT INTO Review (review_text, review_rate, review_date, User_id_user, Song_id_song, Album_id_album, Likes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id_review, review_text, review_rate, review_date, user_id_user, song_id_song, album_id_album, likes
`

type CreateReviewParams struct {
	ReviewText   string        `json:"review_text"`
	ReviewRate   float64       `json:"review_rate"`
	ReviewDate   time.Time     `json:"review_date"`
	UserIDUser   int32         `json:"user_id_user"`
	SongIDSong   sql.NullInt32 `json:"song_id_song"`
	AlbumIDAlbum sql.NullInt32 `json:"album_id_album"`
	Likes        int32         `json:"likes"`
}

// REVIEW QUERIES
func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, createReview,
		arg.ReviewText,
		arg.ReviewRate,
		arg.ReviewDate,
		arg.UserIDUser,
		arg.SongIDSong,
		arg.AlbumIDAlbum,
		arg.Likes,
	)
	var i Review
	err := row.Scan(
		&i.IDReview,
		&i.ReviewText,
		&i.ReviewRate,
		&i.ReviewDate,
		&i.UserIDUser,
		&i.SongIDSong,
		&i.AlbumIDAlbum,
		&i.Likes,
	)
	return i, err
}

const createSong = `-- name: CreateSong :one

INSERT INTO Song (song_name, song_dur, Album_id_album, likes)
VALUES ($1, $2, $3, $4)
RETURNING id_song, song_name, song_dur, likes, album_id_album
`

type CreateSongParams struct {
	SongName     string `json:"song_name"`
	SongDur      int32  `json:"song_dur"`
	AlbumIDAlbum int32  `json:"album_id_album"`
	Likes        int32  `json:"likes"`
}

// QUERIES DE SONG
func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (Song, error) {
	row := q.db.QueryRowContext(ctx, createSong,
		arg.SongName,
		arg.SongDur,
		arg.AlbumIDAlbum,
		arg.Likes,
	)
	var i Song
	err := row.Scan(
		&i.IDSong,
		&i.SongName,
		&i.SongDur,
		&i.Likes,
		&i.AlbumIDAlbum,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO "User" (user_name, amigos, photo)
VALUES ($1, $2, $3)
RETURNING id_user, user_name, amigos, photo
`

type CreateUserParams struct {
	UserName string `json:"user_name"`
	Amigos   int32  `json:"amigos"`
	Photo    int32  `json:"photo"`
}

// QUERIES DE USER
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.UserName, arg.Amigos, arg.Photo)
	var i User
	err := row.Scan(
		&i.IDUser,
		&i.UserName,
		&i.Amigos,
		&i.Photo,
	)
	return i, err
}

const deleteAlbum = `-- name: DeleteAlbum :exec
DELETE FROM Album
WHERE id_album = $1
`

func (q *Queries) DeleteAlbum(ctx context.Context, idAlbum int32) error {
	_, err := q.db.ExecContext(ctx, deleteAlbum, idAlbum)
	return err
}

const deleteArtist = `-- name: DeleteArtist :exec
DELETE FROM Artist
WHERE id_artist = $1
`

func (q *Queries) DeleteArtist(ctx context.Context, idArtist int32) error {
	_, err := q.db.ExecContext(ctx, deleteArtist, idArtist)
	return err
}

const deleteArtistSong = `-- name: DeleteArtistSong :exec
DELETE FROM Artist_Song
WHERE Artist_id_artist = $1 AND Song_id_song = $2
`

type DeleteArtistSongParams struct {
	ArtistIDArtist int32 `json:"artist_id_artist"`
	SongIDSong     int32 `json:"song_id_song"`
}

func (q *Queries) DeleteArtistSong(ctx context.Context, arg DeleteArtistSongParams) error {
	_, err := q.db.ExecContext(ctx, deleteArtistSong, arg.ArtistIDArtist, arg.SongIDSong)
	return err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM Review
WHERE id_review = $1
`

func (q *Queries) DeleteReview(ctx context.Context, idReview int32) error {
	_, err := q.db.ExecContext(ctx, deleteReview, idReview)
	return err
}

const deleteSong = `-- name: DeleteSong :exec
DELETE FROM Song
WHERE id_song = $1
`

func (q *Queries) DeleteSong(ctx context.Context, idSong int32) error {
	_, err := q.db.ExecContext(ctx, deleteSong, idSong)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "User"
WHERE id_user = $1
`

func (q *Queries) DeleteUser(ctx context.Context, idUser int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, idUser)
	return err
}

const getAlbumByArtist = `-- name: GetAlbumByArtist :many
SELECT id_album, album_name, album_dur, album_ph, release_date, artist_id_artist, likes FROM Album
WHERE Artist_id_artist = $1
`

func (q *Queries) GetAlbumByArtist(ctx context.Context, artistIDArtist int32) ([]Album, error) {
	rows, err := q.db.QueryContext(ctx, getAlbumByArtist, artistIDArtist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.IDAlbum,
			&i.AlbumName,
			&i.AlbumDur,
			&i.AlbumPh,
			&i.ReleaseDate,
			&i.ArtistIDArtist,
			&i.Likes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlbumLikes = `-- name: GetAlbumLikes :many
SELECT SUM(Likes) AS Total_likes
FROM Album
WHERE id_album = $1
`

func (q *Queries) GetAlbumLikes(ctx context.Context, idAlbum int32) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getAlbumLikes, idAlbum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var total_likes int64
		if err := rows.Scan(&total_likes); err != nil {
			return nil, err
		}
		items = append(items, total_likes)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlbumSongById = `-- name: GetAlbumSongById :one
SELECT  Album_id_album 
FROM Song
WHERE id_song = $1
`

func (q *Queries) GetAlbumSongById(ctx context.Context, idSong int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getAlbumSongById, idSong)
	var album_id_album int32
	err := row.Scan(&album_id_album)
	return album_id_album, err
}

const getAlbumSongByName = `-- name: GetAlbumSongByName :many
SELECT  Album_id_album 
FROM Song
WHERE song_name = $1
`

func (q *Queries) GetAlbumSongByName(ctx context.Context, songName string) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAlbumSongByName, songName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var album_id_album int32
		if err := rows.Scan(&album_id_album); err != nil {
			return nil, err
		}
		items = append(items, album_id_album)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistById = `-- name: GetArtistById :one
SELECT id_artist, artist_name, photo, artist_bio FROM Artist
WHERE id_artist = $1
`

func (q *Queries) GetArtistById(ctx context.Context, idArtist int32) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtistById, idArtist)
	var i Artist
	err := row.Scan(
		&i.IDArtist,
		&i.ArtistName,
		&i.Photo,
		&i.ArtistBio,
	)
	return i, err
}

const getArtistByName = `-- name: GetArtistByName :many
SELECT id_artist, artist_name, photo, artist_bio FROM Artist
WHERE artist_name = $1
`

func (q *Queries) GetArtistByName(ctx context.Context, artistName string) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, getArtistByName, artistName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.IDArtist,
			&i.ArtistName,
			&i.Photo,
			&i.ArtistBio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistSong = `-- name: GetArtistSong :one
SELECT artist_id_artist, song_id_song, roll FROM Artist_Song
WHERE Artist_id_artist = $1 AND Song_id_song = $2
`

type GetArtistSongParams struct {
	ArtistIDArtist int32 `json:"artist_id_artist"`
	SongIDSong     int32 `json:"song_id_song"`
}

func (q *Queries) GetArtistSong(ctx context.Context, arg GetArtistSongParams) (ArtistSong, error) {
	row := q.db.QueryRowContext(ctx, getArtistSong, arg.ArtistIDArtist, arg.SongIDSong)
	var i ArtistSong
	err := row.Scan(&i.ArtistIDArtist, &i.SongIDSong, &i.Roll)
	return i, err
}

const getArtistsBySong = `-- name: GetArtistsBySong :many
SELECT artist_id_artist, song_id_song, roll FROM Artist_Song
WHERE Song_id_song = $1
`

func (q *Queries) GetArtistsBySong(ctx context.Context, songIDSong int32) ([]ArtistSong, error) {
	rows, err := q.db.QueryContext(ctx, getArtistsBySong, songIDSong)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtistSong
	for rows.Next() {
		var i ArtistSong
		if err := rows.Scan(&i.ArtistIDArtist, &i.SongIDSong, &i.Roll); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReview = `-- name: GetReview :one
SELECT id_review, review_text, review_rate, review_date, user_id_user, song_id_song, album_id_album, likes FROM Review
WHERE id_review = $1
`

func (q *Queries) GetReview(ctx context.Context, idReview int32) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReview, idReview)
	var i Review
	err := row.Scan(
		&i.IDReview,
		&i.ReviewText,
		&i.ReviewRate,
		&i.ReviewDate,
		&i.UserIDUser,
		&i.SongIDSong,
		&i.AlbumIDAlbum,
		&i.Likes,
	)
	return i, err
}

const getReviewLikes = `-- name: GetReviewLikes :one
SELECT sum(likes) as review_likes
FROM Review
WHERE id_review = $1
`

func (q *Queries) GetReviewLikes(ctx context.Context, idReview int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getReviewLikes, idReview)
	var review_likes int64
	err := row.Scan(&review_likes)
	return review_likes, err
}

const getSongByAlbum = `-- name: GetSongByAlbum :many
SELECT id_song, song_name, song_dur, likes, album_id_album FROM Song
WHERE Album_id_album = $1
`

func (q *Queries) GetSongByAlbum(ctx context.Context, albumIDAlbum int32) ([]Song, error) {
	rows, err := q.db.QueryContext(ctx, getSongByAlbum, albumIDAlbum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.IDSong,
			&i.SongName,
			&i.SongDur,
			&i.Likes,
			&i.AlbumIDAlbum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongById = `-- name: GetSongById :one
SELECT id_song, song_name, song_dur, likes, album_id_album FROM Song
WHERE id_song = $1
`

func (q *Queries) GetSongById(ctx context.Context, idSong int32) (Song, error) {
	row := q.db.QueryRowContext(ctx, getSongById, idSong)
	var i Song
	err := row.Scan(
		&i.IDSong,
		&i.SongName,
		&i.SongDur,
		&i.Likes,
		&i.AlbumIDAlbum,
	)
	return i, err
}

const getSongByName = `-- name: GetSongByName :many
SELECT id_song, song_name, song_dur, likes, album_id_album FROM Song
WHERE song_name = $1
`

func (q *Queries) GetSongByName(ctx context.Context, songName string) ([]Song, error) {
	rows, err := q.db.QueryContext(ctx, getSongByName, songName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.IDSong,
			&i.SongName,
			&i.SongDur,
			&i.Likes,
			&i.AlbumIDAlbum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongLikes = `-- name: GetSongLikes :one
SELECT SUM(Likes) AS Total_likes
FROM Song
WHERE id_song = $1
`

func (q *Queries) GetSongLikes(ctx context.Context, idSong int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSongLikes, idSong)
	var total_likes int64
	err := row.Scan(&total_likes)
	return total_likes, err
}

const getSongsByArtist = `-- name: GetSongsByArtist :many
SELECT artist_id_artist, song_id_song, roll FROM Artist_Song
WHERE Artist_id_artist = $1
`

func (q *Queries) GetSongsByArtist(ctx context.Context, artistIDArtist int32) ([]ArtistSong, error) {
	rows, err := q.db.QueryContext(ctx, getSongsByArtist, artistIDArtist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtistSong
	for rows.Next() {
		var i ArtistSong
		if err := rows.Scan(&i.ArtistIDArtist, &i.SongIDSong, &i.Roll); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserById = `-- name: GetUserById :one
SELECT id_user, user_name, amigos, photo FROM "User"
WHERE id_user = $1
`

func (q *Queries) GetUserById(ctx context.Context, idUser int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, idUser)
	var i User
	err := row.Scan(
		&i.IDUser,
		&i.UserName,
		&i.Amigos,
		&i.Photo,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :many
SELECT id_user, user_name, amigos, photo FROM "User"
WHERE user_name = $1
`

func (q *Queries) GetUserByName(ctx context.Context, userName string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUserByName, userName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.IDUser,
			&i.UserName,
			&i.Amigos,
			&i.Photo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbums = `-- name: ListAlbums :many
SELECT id_album, album_name, album_dur, album_ph, release_date, artist_id_artist, likes FROM Album
ORDER BY album_name
`

func (q *Queries) ListAlbums(ctx context.Context) ([]Album, error) {
	rows, err := q.db.QueryContext(ctx, listAlbums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.IDAlbum,
			&i.AlbumName,
			&i.AlbumDur,
			&i.AlbumPh,
			&i.ReleaseDate,
			&i.ArtistIDArtist,
			&i.Likes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistSongs = `-- name: ListArtistSongs :many
SELECT artist_id_artist, song_id_song, roll FROM Artist_Song
`

func (q *Queries) ListArtistSongs(ctx context.Context) ([]ArtistSong, error) {
	rows, err := q.db.QueryContext(ctx, listArtistSongs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtistSong
	for rows.Next() {
		var i ArtistSong
		if err := rows.Scan(&i.ArtistIDArtist, &i.SongIDSong, &i.Roll); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtists = `-- name: ListArtists :many
SELECT id_artist, artist_name, photo, artist_bio FROM Artist
ORDER BY id_artist
`

func (q *Queries) ListArtists(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, listArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.IDArtist,
			&i.ArtistName,
			&i.Photo,
			&i.ArtistBio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviews = `-- name: ListReviews :many
SELECT id_review, review_text, review_rate, review_date, user_id_user, song_id_song, album_id_album, likes FROM Review
ORDER BY id_review
`

func (q *Queries) ListReviews(ctx context.Context) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, listReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.IDReview,
			&i.ReviewText,
			&i.ReviewRate,
			&i.ReviewDate,
			&i.UserIDUser,
			&i.SongIDSong,
			&i.AlbumIDAlbum,
			&i.Likes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongs = `-- name: ListSongs :many
SELECT id_song, song_name, song_dur, likes, album_id_album FROM Song
ORDER BY id_song
`

func (q *Queries) ListSongs(ctx context.Context) ([]Song, error) {
	rows, err := q.db.QueryContext(ctx, listSongs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.IDSong,
			&i.SongName,
			&i.SongDur,
			&i.Likes,
			&i.AlbumIDAlbum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id_user, user_name, amigos, photo FROM "User"
ORDER BY id_user
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.IDUser,
			&i.UserName,
			&i.Amigos,
			&i.Photo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlbum = `-- name: UpdateAlbum :exec
UPDATE Album
SET album_name = $2, album_dur = $3, album_ph = $4, release_date = $5, Artist_id_artist = $6, Likes = $7
WHERE id_album = $1
`

type UpdateAlbumParams struct {
	IDAlbum        int32     `json:"id_album"`
	AlbumName      string    `json:"album_name"`
	AlbumDur       int32     `json:"album_dur"`
	AlbumPh        int32     `json:"album_ph"`
	ReleaseDate    time.Time `json:"release_date"`
	ArtistIDArtist int32     `json:"artist_id_artist"`
	Likes          int32     `json:"likes"`
}

func (q *Queries) UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) error {
	_, err := q.db.ExecContext(ctx, updateAlbum,
		arg.IDAlbum,
		arg.AlbumName,
		arg.AlbumDur,
		arg.AlbumPh,
		arg.ReleaseDate,
		arg.ArtistIDArtist,
		arg.Likes,
	)
	return err
}

const updateArtist = `-- name: UpdateArtist :one
UPDATE Artist
SET artist_name = $2, photo = $3, artist_bio = $4
WHERE id_artist = $1
RETURNING id_artist, artist_name, photo, artist_bio
`

type UpdateArtistParams struct {
	IDArtist   int32  `json:"id_artist"`
	ArtistName string `json:"artist_name"`
	Photo      int32  `json:"photo"`
	ArtistBio  string `json:"artist_bio"`
}

func (q *Queries) UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error) {
	row := q.db.QueryRowContext(ctx, updateArtist,
		arg.IDArtist,
		arg.ArtistName,
		arg.Photo,
		arg.ArtistBio,
	)
	var i Artist
	err := row.Scan(
		&i.IDArtist,
		&i.ArtistName,
		&i.Photo,
		&i.ArtistBio,
	)
	return i, err
}

const updateArtistSong = `-- name: UpdateArtistSong :one
UPDATE Artist_Song
SET Roll = $3
WHERE Artist_id_artist = $1 AND Song_id_song = $2
RETURNING artist_id_artist, song_id_song, roll
`

type UpdateArtistSongParams struct {
	ArtistIDArtist int32 `json:"artist_id_artist"`
	SongIDSong     int32 `json:"song_id_song"`
	Roll           bool  `json:"roll"`
}

func (q *Queries) UpdateArtistSong(ctx context.Context, arg UpdateArtistSongParams) (ArtistSong, error) {
	row := q.db.QueryRowContext(ctx, updateArtistSong, arg.ArtistIDArtist, arg.SongIDSong, arg.Roll)
	var i ArtistSong
	err := row.Scan(&i.ArtistIDArtist, &i.SongIDSong, &i.Roll)
	return i, err
}

const updateReview = `-- name: UpdateReview :one
UPDATE Review
SET review_text = $2, review_rate = $3, review_date = $4, User_id_user = $5, Song_id_song = $6, Album_id_album = $7, Likes = $8
WHERE id_review = $1
RETURNING id_review, review_text, review_rate, review_date, user_id_user, song_id_song, album_id_album, likes
`

type UpdateReviewParams struct {
	IDReview     int32         `json:"id_review"`
	ReviewText   string        `json:"review_text"`
	ReviewRate   float64       `json:"review_rate"`
	ReviewDate   time.Time     `json:"review_date"`
	UserIDUser   int32         `json:"user_id_user"`
	SongIDSong   sql.NullInt32 `json:"song_id_song"`
	AlbumIDAlbum sql.NullInt32 `json:"album_id_album"`
	Likes        int32         `json:"likes"`
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, updateReview,
		arg.IDReview,
		arg.ReviewText,
		arg.ReviewRate,
		arg.ReviewDate,
		arg.UserIDUser,
		arg.SongIDSong,
		arg.AlbumIDAlbum,
		arg.Likes,
	)
	var i Review
	err := row.Scan(
		&i.IDReview,
		&i.ReviewText,
		&i.ReviewRate,
		&i.ReviewDate,
		&i.UserIDUser,
		&i.SongIDSong,
		&i.AlbumIDAlbum,
		&i.Likes,
	)
	return i, err
}

const updateSong = `-- name: UpdateSong :one
UPDATE Song
SET song_name = $2, song_dur = $3, likes = $4
WHERE id_song = $1
RETURNING id_song, song_name, song_dur, likes, album_id_album
`

type UpdateSongParams struct {
	IDSong   int32  `json:"id_song"`
	SongName string `json:"song_name"`
	SongDur  int32  `json:"song_dur"`
	Likes    int32  `json:"likes"`
}

func (q *Queries) UpdateSong(ctx context.Context, arg UpdateSongParams) (Song, error) {
	row := q.db.QueryRowContext(ctx, updateSong,
		arg.IDSong,
		arg.SongName,
		arg.SongDur,
		arg.Likes,
	)
	var i Song
	err := row.Scan(
		&i.IDSong,
		&i.SongName,
		&i.SongDur,
		&i.Likes,
		&i.AlbumIDAlbum,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE "User"
SET user_name = $2, amigos = $3, photo = $4
WHERE id_user = $1
RETURNING id_user, user_name, amigos, photo
`

type UpdateUserParams struct {
	IDUser   int32  `json:"id_user"`
	UserName string `json:"user_name"`
	Amigos   int32  `json:"amigos"`
	Photo    int32  `json:"photo"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.IDUser,
		arg.UserName,
		arg.Amigos,
		arg.Photo,
	)
	var i User
	err := row.Scan(
		&i.IDUser,
		&i.UserName,
		&i.Amigos,
		&i.Photo,
	)
	return i, err
}
